/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Eletrodomesticos;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Aluno
 */
public class JIAdd extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIAdd
     */
    public JIAdd() {
        initComponents();
        JTextField args[] = {txtProduto, txtMarca, txtQtd};
        Limpador.desativaform(args);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        lblIdAdd = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        lblProdutoAdd = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblMarcaAdd = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lblRemover = new javax.swing.JLabel();
        txtRemover = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setClosable(true);
        setTitle("Adicionar quantidade");
        setToolTipText("");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        lblIdAdd.setText("Digite o ID do produto:");

        lblAdd.setText("Adicionar:");

        txtAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddKeyTyped(evt);
            }
        });

        lblProdutoAdd.setForeground(new java.awt.Color(114, 114, 114));
        lblProdutoAdd.setText("Produto:");

        txtMarca.setForeground(new java.awt.Color(114, 114, 114));

        lblMarcaAdd.setForeground(new java.awt.Color(114, 114, 114));
        lblMarcaAdd.setText("Marca:");

        txtQtd.setForeground(new java.awt.Color(114, 114, 114));

        jLabel1.setForeground(new java.awt.Color(114, 114, 114));
        jLabel1.setText("Quantidade atual:");

        txtProduto.setForeground(new java.awt.Color(114, 114, 114));

        lblRemover.setText("Remover:");

        txtRemover.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRemoverKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRemoverKeyTyped(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Lupa search.png"))); // NOI18N
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIdAdd)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMarcaAdd)
                            .addComponent(lblProdutoAdd)
                            .addComponent(jLabel1)
                            .addComponent(lblAdd)
                            .addComponent(lblRemover))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIdAdd)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdutoAdd)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaAdd)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdd)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRemover)
                    .addComponent(txtRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSearch.doClick();
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(txtId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ID não digitado.");
        }else{
            if(txtAdd.getText().equals("") && txtRemover.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Nenhum valor inserido.");
                txtAdd.requestFocus();
            }else{
                Eletrodomesticos produtos = new Eletrodomesticos();
                produtos.Addqtd(txtQtd, txtAdd, txtRemover, txtId, txtProduto, txtMarca); 
            }
        }    
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        JTextField args[] = {txtId, txtProduto, txtMarca, txtQtd, txtAdd, txtRemover};
        Limpador.limpaform(args);
        txtId.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(txtId.getText().equals("") && txtProduto.getText().equals("") && txtMarca.getText().equals("") && txtQtd.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite algum ID.");
            txtAdd.setText("");
            txtRemover.setText("");
        }else if(txtId.getText().equals("")){
            JTextField s[] = {txtId, txtProduto, txtMarca, txtQtd, txtAdd, txtRemover, txtAdd, txtRemover};
            Limpador.limpaform(s);
        }else{
            JTextField args[] = {txtProduto, txtMarca, txtQtd};
            Eletrodomesticos.ARID(txtId.getText(), args);
            txtAdd.requestFocus();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        Verificador.Apenas_numeros(evt);
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyTyped
        Verificador.Apenas_numeros(evt);
    }//GEN-LAST:event_txtAddKeyTyped

    private void txtRemoverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemoverKeyTyped
        Verificador.Apenas_numeros(evt);
    }//GEN-LAST:event_txtRemoverKeyTyped

    private void txtAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAlterar.doClick();   
        }
    }//GEN-LAST:event_txtAddKeyPressed

    private void txtRemoverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemoverKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAlterar.doClick();   
        }
    }//GEN-LAST:event_txtRemoverKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblIdAdd;
    private javax.swing.JLabel lblMarcaAdd;
    private javax.swing.JLabel lblProdutoAdd;
    private javax.swing.JLabel lblRemover;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtRemover;
    // End of variables declaration//GEN-END:variables
}
